version: '3.9'
services:
  app:
    build:
      context: .
      args:
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
        SOURCE_VERSION: ${SOURCE_VERSION}
    image: forum_project-image
    container_name: forum_project-container
    env_file:
      - ./webapp/.env
      - ./backend/.env
      - ./.env.docker
    environment:
      - MODEL_API_URL=http://model:8000
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - model

  model:
    build:
      context: ./backend/python-model
    image: forum_model-image
    container_name: forum_model-container
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_DATA_PATH=/app/data/df_combined.csv
    ports:
      - '8000:8000'